<?php
	define('SLOODLE_TEST_CONFIG_SLOODLE_URL', 'http://moodle.edochan.com');
	define('SLOODLE_TEST_CONFIG_OBJUUID','315d214c-880b-a03b-7f1f-2afc083b2257');
	define('SLOODLE_TEST_CONFIG_OBJNAME','Sloodle Box');
	define('SLOODLE_TEST_CONFIG_XMLRPC_CHANNEL','6244aebb-2d15-c184-2d47-d6d4aeb33791');
	define('SLOODLE_TEST_CONFIG_MOODLE_ADMIN_USERNAME','admin');
	define('SLOODLE_TEST_CONFIG_MOODLE_ADMIN_PASSWORD','cat$own');
	define('SLOODLE_TEST_CONFIG_MOODLE_REGISTERED_AVATAR_NAME','Edmund Earp');
	define('SLOODLE_TEST_CONFIG_MOODLE_REGISTERED_AVATAR_UUID','746ad236-d28d-4aab-93de-1e09a076c5f3');
	define('SLOODLE_TEST_CONFIG_MOODLE_UNREGISTERED_AVATAR_NAME','Gershwin Klata');
	define('SLOODLE_TEST_CONFIG_MOODLE_UNREGISTERED_AVATAR_UUID','TODO');
	define('SLOODLE_TEST_CONFIG_PRIM_PASSWORD','dfj32aefes');
?>
